# PPT生成工作流配置
workflow:
  name: ppt_generation
  description: "PPT自动生成工作流"
  
  # 节点配置 - 只引用模型类型，具体模型名称从环境变量获取
  nodes:
    - name: markdown_agent
      agent: MarkdownAgent
      config:
        model_type: text  # 对应环境变量LLM_MODEL
        max_retries: 3
        
    - name: ppt_analyzer
      agent: PPTAnalysisAgent  
      config:
        model_type: vision  # 对应环境变量VISION_MODEL
        
    - name: layout_decider
      agent: LayoutDecisionAgent
      config:
        model_type: embedding  # 对应环境变量EMBEDDING_MODEL
        
    - name: ppt_generator
      agent: PPTGeneratorAgent
      config:
        template: "default"
        
    - name: validator
      agent: ValidationAgent
      config:
        model_type: vision  # 对应环境变量VISION_MODEL
        
  # 边配置
  edges:
    - from: start
      to: markdown_agent
    - from: markdown_agent
      to: ppt_analyzer
    - from: ppt_analyzer
      to: layout_decider
    - from: layout_decider
      to: ppt_generator
    - from: ppt_generator
      to: validator
      condition: 
        pass: end
        retry: ppt_generator 