# PPT生成工作流配置
workflow:
  name: ppt_generation
  description: "PPT自动生成工作流"
  
  # 节点配置
  nodes:
    - name: markdown_parser
      agent: MarkdownAgent
      config:
        llm_model: gpt-4
        max_retries: 3
        
    - name: ppt_analyzer
      agent: PPTAnalysisAgent  
      config:
        vision_model: gpt-4-vision
        
    - name: layout_decider
      agent: LayoutDecisionAgent
      config:
        embedding_model: text-embedding-3-large
        
    - name: ppt_generator
      agent: PPTGeneratorAgent
      config:
        template: "default"
        
    - name: validator
      agent: ValidationAgent
      config:
        vision_model: gpt-4-vision
        
  # 边配置
  edges:
    - from: start
      to: markdown_parser
    - from: markdown_parser
      to: ppt_analyzer
    - from: ppt_analyzer
      to: layout_decider
    - from: layout_decider
      to: ppt_generator
    - from: ppt_generator
      to: validator
      condition: 
        pass: end
        retry: ppt_generator 