# PPT生成工作流配置
workflow:
  name: ppt_assisstant
  description: "PPT自动处理工作流"
  
  # 节点配置 - 只引用模型类型，具体模型名称从环境变量获取
  nodes:
    - name: markdown_parser
      agent: MarkdownAgent
      config:
        model_type: text  # 对应环境变量LLM_MODEL
        max_retries: 3
        
    - name: ppt_analyzer
      agent: PPTAnalysisAgent  
      config:
        model_type: vision  # 对应环境变量VISION_MODEL
        
    - name: content_planner
      agent: ContentPlanningAgent
      config:
        model_type: text  # 对应环境变量LLM_MODEL
        
    - name: slide_generator
      agent: SlideGeneratorAgent
      config:
        model_type: text  # 对应环境变量LLM_MODEL
        
    - name: ppt_finalizer
      agent: PPTFinalizerAgent
      config:
        model_type: vision  # 对应环境变量VISION_MODEL
        max_iterations: 3
  
  # 边配置 - 线性流程
  edges:
    - from: start
      to: markdown_parser
    - from: markdown_parser
      to: ppt_analyzer
    - from: ppt_analyzer
      to: content_planner
    - from: content_planner
      to: slide_generator
    - from: slide_generator
      to: ppt_finalizer
    - from: ppt_finalizer
      to: end 