services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ppt-net

volumes:
  redis_data:
  
networks:
  ppt-net:
    driver: bridge 