# 模型配置中心 - 所有模型配置的唯一数据源
providers:
  openai:
    # 默认设置(当未指定时使用)
    default:
      api_base: ${OPENAI_API_BASE:https://api.openai.com/v1}
      api_key: ${OPENAI_API_KEY:}
      organization: ${OPENAI_ORGANIZATION:}
    
    # 按类型定义不同模型组
    model_groups:
      text:
        api_base: ${LLM_API_BASE:${OPENAI_API_BASE:}}  # 级联回退机制
        api_key: ${LLM_API_KEY:${OPENAI_API_KEY:}}
        default_model: gpt-4
        models:
          gpt-4:
            max_tokens: 8192
            temperature: 0.7
          gpt-3.5-turbo:
            max_tokens: 4096
            temperature: 0.7
      
      vision:
        api_base: ${VISION_API_BASE:${OPENAI_API_BASE:}}
        api_key: ${VISION_API_KEY:${OPENAI_API_KEY:}}
        default_model: gpt-4-vision
        models:
          gpt-4-vision:
            max_tokens: 4096
            temperature: 0.7
      
      embedding:
        api_base: ${EMBEDDING_API_BASE:${OPENAI_API_BASE:}}
        api_key: ${EMBEDDING_API_KEY:${OPENAI_API_KEY:}}
        default_model: text-embedding-3-large
        models:
          text-embedding-3-large:
            dimensions: 3072
          text-embedding-3-small:
            dimensions: 1536

# 大模型配置文件

# 提示词配置
prompts:
  # 提示词已移动到单独的配置文件中
  path: config/prompts/ 