# 模型配置
model_providers:
  langgraph:
    workflow_config: config/workflows/
    agent_config: config/agents/
    
  llm:
    - type: openai
      models:
        - name: gpt-4
          api_key_env: OPENAI_API_KEY
          
  vision:
    - type: openai
      models:
        - name: gpt-4-vision
          api_key_env: OPENAI_API_KEY 

# 大模型配置文件

# OpenAI模型配置
openai:
  # 文本模型
  text:
    default: gpt-4
    models:
      - name: gpt-4
        max_tokens: 8192
        temperature: 0.7
      - name: gpt-3.5-turbo
        max_tokens: 4096
        temperature: 0.7
  
  # 嵌入模型  
  embedding:
    default: text-embedding-3-large
    models:
      - name: text-embedding-3-large
        dimensions: 3072
      - name: text-embedding-3-small
        dimensions: 1536
  
  # 视觉模型
  vision:
    default: gpt-4-vision
    models:
      - name: gpt-4-vision
        max_tokens: 4096
        temperature: 0.7

# 模型提示词配置
prompts:
  markdown_parser: |
    你是一个专业的Markdown解析器，请分析以下Markdown内容，提取其中的结构化信息。
    请从以下角度分析:
    1. 内容结构：标题层级关系、列表、表格等
    2. 语义类型：每个部分表达的是什么类型的内容（描述、数据、步骤等）
    3. 关系类型：内容之间的逻辑关系（并列、递进、因果等）
    4. 可视化建议：哪些部分适合用图表、图片等方式展示
    5. 关键点：内容中的关键点和重点
    6. 摘要：对整体内容的简要总结
    
    请将分析结果以JSON格式返回，保持原始内容的结构，同时添加你的分析结果。
    
    Markdown内容:
    ```
    {markdown_content}
    ```
  
  ppt_analyzer: |
    分析以下PPT模板的布局和设计特点。请识别：
    1. 模板名称和整体风格
    2. 可用的布局类型及其特点
    3. 每种布局适合的内容类型
    4. 设计元素和颜色方案
    5. 字体和排版特点
    
    请以JSON格式返回分析结果。
    
  layout_decision: |
    基于以下内容结构和PPT模板分析，为每个内容部分选择最合适的布局：
    
    内容结构:
    {content_structure}
    
    PPT模板分析:
    {template_analysis}
    
    请为每个内容部分选择一个最合适的布局，并解释选择理由。
    返回JSON格式，包含每个幻灯片的内容和对应的布局。 